apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage dev portal for my homelab
  annotations:
    argocd/app-name: backstage
    github.com/project-slug: kdwils/backstage
    backstage.io/kubernetes-id: backstage
  links:
    - url: https://backstage.kyledev.co
      title: backstage
spec:
  type: website
  lifecycle: production
  owner: kdwils
  system: homelab
